import Link from "next/link";
import { Activity, ArrowRight, Bell, ChartNoAxesCombined, Database } from "lucide-react";

export default function LandingPage() {
  return <div className="min-h-screen bg-white text-slate-950">
    <header className="border-b border-slate-200"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 text-sm font-semibold"><Activity className="text-blue-700" size={20}/>TyphoidWatch</Link><div className="flex items-center gap-2"><Link href="/auth/login" className="px-3 py-2 text-sm text-slate-600">Sign in</Link><Link href="/auth/register" className="rounded bg-slate-950 px-4 py-2 text-sm font-medium text-white">Create account</Link></div></div></header>
    <main>
      <section className="mx-auto max-w-6xl px-5 py-20 sm:py-28"><div className="max-w-3xl"><p className="text-sm font-medium text-blue-700">Typhoid surveillance and early warning</p><h1 className="mt-5 text-5xl font-semibold leading-tight tracking-tight sm:text-6xl">Make outbreak risk visible before it spreads.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-500">One secure system for reporting cases, monitoring environmental conditions, predicting district risk, and coordinating public-health response.</p><div className="mt-8 flex gap-3"><Link href="/auth/login" className="flex items-center gap-2 rounded bg-slate-950 px-5 py-3 text-sm font-medium text-white">Open dashboard <ArrowRight size={16}/></Link><Link href="/auth/register" className="rounded border border-slate-300 px-5 py-3 text-sm font-medium">Join as Health Officer</Link></div></div></section>
      <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto grid max-w-6xl divide-y divide-slate-200 px-5 md:grid-cols-3 md:divide-x md:divide-y-0">{[[Database,"Collect","Validated case and environmental records."],[ChartNoAxesCombined,"Predict","Clear district risk and confidence scores."],[Bell,"Respond","Prioritized alerts and practical guidance."]].map(([Icon,title,body])=>{const ItemIcon=Icon as typeof Database;return <div key={String(title)} className="py-10 md:px-8 md:first:pl-0 md:last:pr-0"><ItemIcon size={20} className="text-blue-700"/><h2 className="mt-5 font-semibold">{String(title)}</h2><p className="mt-2 text-sm text-slate-500">{String(body)}</p></div>})}</div></section>
      <section className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 px-5 py-16 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-semibold">Built for coordinated decisions.</h2><p className="mt-2 text-sm text-slate-500">Role-specific access for Health Officers, Government Officials, and Administrators.</p></div><Link href="/auth/login" className="text-sm font-semibold text-blue-700">Access the system →</Link></section>
    </main>
    <footer className="border-t border-slate-200"><div className="mx-auto flex max-w-6xl justify-between px-5 py-6 text-xs text-slate-400"><p>TyphoidWatch Rwanda</p><p>Public-health validation required</p></div></footer>
  </div>;
}
