import Link from "next/link";
import { Activity, ArrowUpRight, BellRing, BrainCircuit, Building2, Database, Map, ShieldCheck, Stethoscope } from "lucide-react";

const workflow = [
  ["01", "Report", "Health officers submit clinical and geographic case information."],
  ["02", "Validate", "Authorized reviewers verify records before analytical use."],
  ["03", "Predict", "Case trends and environmental conditions generate district risk."],
  ["04", "Respond", "Alerts and reports coordinate regional and national action."],
] as const;

export default function LandingPage() {
  return <div className="min-h-screen bg-[#f4f5f7] text-slate-950">
    <header className="border-b border-slate-300 bg-[#f4f5f7]"><div className="mx-auto flex h-16 max-w-[1400px] items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-2 text-sm font-black"><span className="grid size-8 place-items-center rounded bg-blue-700 text-white"><Activity size={17}/></span>TyphoidWatch / RW</Link><nav className="hidden gap-8 text-xs font-bold uppercase tracking-wider text-slate-500 md:flex"><a href="#mission">Mission</a><a href="#workflow">Workflow</a><a href="#roles">Access</a></nav><Link href="/auth/login" className="flex items-center gap-2 rounded border border-slate-950 px-3 py-2 text-xs font-bold">Enter system <ArrowUpRight size={14}/></Link></div></header>

    <main>
      <section id="mission" className="border-b border-slate-300"><div className="mx-auto grid max-w-[1400px] lg:grid-cols-[1fr_360px]"><div className="border-slate-300 px-5 py-16 lg:border-r lg:px-8 lg:py-24"><p className="mb-8 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-blue-700"><ShieldCheck size={15}/> Rwanda disease surveillance infrastructure</p><h1 className="max-w-5xl text-[clamp(3.2rem,7vw,7.5rem)] font-black leading-[.86] tracking-[-.06em]">INTELLIGENCE<br/>FOR EARLIER<br/><span className="text-blue-700">ACTION.</span></h1><div className="mt-10 flex max-w-3xl flex-col gap-6 border-t border-slate-300 pt-6 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-xl text-base leading-7 text-slate-600">A national workspace for detecting typhoid risk from validated case reports and environmental evidence—before local transmission becomes a wider outbreak.</p><Link href="/auth/register" className="shrink-0 rounded bg-slate-950 px-5 py-3 text-sm font-bold text-white">Join as Health Officer</Link></div></div>
        <aside className="grid bg-white lg:grid-rows-[auto_1fr_auto]"><div className="border-b border-slate-300 p-6"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider">System status</p><span className="size-2 rounded bg-blue-600"/></div><p className="mt-2 text-xs text-slate-500">Surveillance services operational</p></div><div className="grid content-center gap-8 p-6"><div><span className="text-6xl font-black">30</span><p className="mt-1 text-xs uppercase tracking-wider text-slate-500">Districts in national scope</p></div><div className="h-px bg-slate-200"/><div><span className="text-6xl font-black">24/7</span><p className="mt-1 text-xs uppercase tracking-wider text-slate-500">Continuous risk visibility</p></div></div><div className="border-t border-slate-300 bg-blue-700 p-6 text-white"><BellRing size={20}/><p className="mt-8 text-sm font-bold">Priority signals reach the people responsible for public-health response.</p></div></aside>
      </div></section>

      <section id="workflow" className="border-b border-slate-300 bg-white"><div className="mx-auto max-w-[1400px] px-5 py-16 lg:px-8"><div className="mb-10 grid gap-4 md:grid-cols-2"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">Operational workflow</p><h2 className="text-3xl font-black tracking-tight md:text-4xl">One governed path from frontline evidence to coordinated response.</h2></div><div className="grid border-l border-t border-slate-300 md:grid-cols-4">{workflow.map(([number,title,body])=><article key={number} className="min-h-64 border-b border-r border-slate-300 p-5"><span className="font-mono text-xs text-blue-700">{number}</span><h3 className="mt-16 text-2xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{body}</p></article>)}</div></div></section>

      <section className="border-b border-slate-300"><div className="mx-auto grid max-w-[1400px] md:grid-cols-3">{[[Database,"Unified evidence","Clinical cases and environmental observations share one controlled data layer."],[BrainCircuit,"Explainable output","Every prediction includes probability, confidence, expected cases, and guidance."],[Map,"Regional visibility","District intelligence rolls into a national view without losing local context."]].map(([Icon,title,body])=>{const ItemIcon=Icon as typeof Database;return <article key={String(title)} className="border-b border-slate-300 p-8 md:border-b-0 md:border-r last:border-r-0"><ItemIcon/><h3 className="mt-10 text-lg font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{String(body)}</p></article>})}</div></section>

      <section id="roles" className="bg-slate-950 text-white"><div className="mx-auto max-w-[1400px] px-5 py-16 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-300">Role-based operations</p><div className="mt-8 grid gap-px bg-slate-700 md:grid-cols-3">{[[Stethoscope,"Health Officers","Report and validate cases, record environmental conditions, generate predictions, and respond to alerts."],[Building2,"Government Officials","Review national statistics, compare regional risk, monitor high-priority alerts, and access reports."],[ShieldCheck,"Administrators","Govern users, model versions, settings, surveillance records, reporting, and audit activity."]].map(([Icon,title,body])=>{const RoleIcon=Icon as typeof Stethoscope;return <article key={String(title)} className="bg-slate-950 p-7"><RoleIcon className="text-blue-300"/><h3 className="mt-8 text-xl font-black">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{String(body)}</p></article>})}</div><div className="mt-10 flex flex-wrap items-center justify-between gap-5 border-t border-slate-700 pt-8"><p className="max-w-xl text-sm text-slate-400">Access is secured through verified accounts and role-specific authorization.</p><div className="flex gap-3"><Link href="/auth/login" className="rounded bg-white px-5 py-2.5 text-sm font-bold text-slate-950">Sign in</Link><Link href="/auth/register" className="rounded border border-slate-600 px-5 py-2.5 text-sm font-bold">Request Health Officer access</Link></div></div></div></section>
    </main>
    <footer className="border-t border-slate-800 bg-slate-950 text-slate-500"><div className="mx-auto flex max-w-[1400px] flex-wrap justify-between gap-3 px-5 py-6 text-xs lg:px-8"><p>© 2026 TyphoidWatch Rwanda</p><p>AI-assisted outputs require qualified public-health validation.</p></div></footer>
  </div>;
}
