"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import { authClient } from "@/lib/auth-client";

function GoogleMark() { return <svg viewBox="0 0 24 24" className="size-4" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.8h5.4a4.6 4.6 0 0 1-2 3v2.5h3.2c1.9-1.8 3-4.3 3-7.3Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.6-2.4l-3.2-2.5c-.9.6-2 1-3.4 1a5.8 5.8 0 0 1-5.5-4H3.2v2.6A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.5 14a6 6 0 0 1 0-3.9V7.5H3.2a10 10 0 0 0 0 9.1L6.5 14Z"/><path fill="#EA4335" d="M12 5.9c1.5 0 2.8.5 3.8 1.5l2.9-2.8A9.7 9.7 0 0 0 3.2 7.5L6.5 10A5.8 5.8 0 0 1 12 6Z"/></svg> }

export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const router = useRouter(); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const inputClass = "mt-1 w-full rounded border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-700 focus:ring-2 focus:ring-blue-100";
  async function socialSignIn() { setError(""); setPending(true); const result = await authClient.signIn.social({ provider: "google", callbackURL: "/auth/redirect" }); if (result?.error) { setError(result.error.message ?? "Google sign-in could not be started."); setPending(false); } }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const email = String(form.get("email")); const password = String(form.get("password")); if (mode === "login") { const result = await authClient.signIn.email({ email, password }); if (result.error) { setError(result.error.message ?? "Unable to sign in"); setPending(false); return; } router.push("/auth/redirect"); router.refresh(); return; } const result = await authClient.signUp.email({ name: String(form.get("name")), email, password }); if (result.error) { setError(result.error.message ?? "Unable to register"); setPending(false); return; } await authClient.emailOtp.sendVerificationOtp({ email, type: "email-verification" }); router.push(`/auth/verify?email=${encodeURIComponent(email)}`); }
  return <div><button type="button" disabled={pending} onClick={socialSignIn} className="flex w-full items-center justify-center gap-2 rounded border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-60"><GoogleMark/> Continue with Google</button><div className="my-3 flex items-center gap-3"><span className="h-px flex-1 bg-slate-200"/><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">or use email</span><span className="h-px flex-1 bg-slate-200"/></div><form onSubmit={submit} className="space-y-2.5">{mode === "register" && <label className="block text-xs font-semibold text-slate-700">Full name<input name="name" required autoComplete="name" className={inputClass}/></label>}<label className="block text-xs font-semibold text-slate-700">Work email<input name="email" type="email" required autoComplete="email" className={inputClass}/></label><label className="block text-xs font-semibold text-slate-700">Password<input name="password" type="password" minLength={8} required autoComplete={mode === "login" ? "current-password" : "new-password"} className={inputClass}/></label>{mode === "login" && <div className="text-right"><Link href="/auth/forgot-password" className="text-xs font-semibold text-blue-700">Forgot password?</Link></div>}{error && <p className="rounded border border-rose-200 bg-rose-50 px-3 py-2 text-xs text-rose-700">{error}</p>}<button disabled={pending} className="flex w-full items-center justify-center rounded bg-blue-900 px-3 py-2.5 text-sm font-bold text-white hover:bg-blue-950 disabled:opacity-60">{pending && <Loader2 className="mr-2 animate-spin" size={14}/>} {mode === "login" ? "Sign in securely" : "Create Health Officer account"}</button><p className="pt-1 text-center text-xs text-slate-500">{mode === "login" ? "New to TyphoidWatch?" : "Already registered?"} <Link className="font-bold text-blue-700" href={mode === "login" ? "/auth/register" : "/auth/login"}>{mode === "login" ? "Create account" : "Sign in"}</Link></p></form></div>;
}
